# Generated by Django 5.2.8 on 2026-05-12 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_fournisseur_facture_lignefacture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignecommande',
            name='article',
        ),
        migrations.RemoveField(
            model_name='lignelivraison',
            name='article',
        ),
        migrations.RemoveField(
            model_name='lignefacture',
            name='article',
        ),
        migrations.RemoveField(
            model_name='boncommande',
            name='client',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='bon',
        ),
        migrations.RemoveField(
            model_name='bonlivraison',
            name='client',
        ),
        migrations.RemoveField(
            model_name='lignelivraison',
            name='bon',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='client',
        ),
        migrations.RemoveField(
            model_name='lignefacture',
            name='facture',
        ),
        migrations.DeleteModel(
            name='Fournisseur',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='BonCommande',
        ),
        migrations.DeleteModel(
            name='LigneCommande',
        ),
        migrations.DeleteModel(
            name='BonLivraison',
        ),
        migrations.DeleteModel(
            name='LigneLivraison',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
        migrations.DeleteModel(
            name='LigneFacture',
        ),
    ]
