# Generated by Django 5.2.8 on 2026-05-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
